### ISSUE TITLE
Add more options on init

### ISSUE THREAD

**Issue by humitos** [kartenkarsten/leaflet-layer-overpass#11]
I have to change some things in the source code to make it more compatible with my situation. Here you can see what are those changes:
 * https://github.com/humitos/osm-pois/commit/021b30a6ae261d9b58f363506a2403ad4ba5b95c

I think we need a way to pass:
 * a function to be called after/before sending the GET request (I'm using this to show a spinner -but maybe I can do this after/before calling `new L.OverPassLayer`). Not sure if this is too important
 * the position for MinZoomIndecator (I want it at `topright`, for example)
 * the text displayed in MinZoomIndecator (I need it in Spanish)

Also, I think the style created for the container of MinZoomIndecator shouldn't be there because the `leaflet-control-minZoomIndecator` is already used. That is the correct place to add more styling. Don't you think?

If you think those things are correct, I will try to prepare a pull request.

**Comment by kartenkarsten** [comment]
From my point of view its a good idea to show a spinner while loading - I don't mind if it's customizable.
Furthermore I totaly agree that the MinZoomIndecator has to become much more flexable.

I don't quite understand where do you think to place the style of `leaflet-control-minZoomIndecator`. Maybe in the Constructor?!

all your points seam to me good ones - so I would like to see a pull request
