### ISSUE TITLE
Add git tags for bower version

### ISSUE THREAD

**Issue by k-nut** [kartenkarsten/leaflet-layer-overpass#13]
We should use `git tag` or the [github release feature](https://github.com/blog/1547-release-your-software) to tag the version of the project. This will lead to bower being able to list versions. [This tutorial](http://bob.yexley.net/creating-and-maintaining-your-own-bower-package/) explains the workflow quite nicely.
Maybe we can provide a `1.0.0` with the latest commits and then provide a `1.1.0` or so when the newest Pull Request is merged.

**Comment by kartenkarsten** [comment]
Thanks that you guide me - it just worked fine and bower understands the version information
