### ISSUE TITLE
Many parallel requests on Overpass API

### ISSUE THREAD

**Issue by mmd-osm** [kartenkarsten/leaflet-layer-overpass#29]
Hi,

I've already opened a similar issue for briefkastenkarte: https://github.com/dbretschneider/briefkastenkarte.de/issues/8. As stated by someone else, this repo is probably a better place to report it... Please check this issue first for a detailed issue description + recommendations.

Basically, splitting up a (rather small) bbox into many small parts and trying to load them in parallel is not the most efficient approach, given that Overpass API will only handle one request at a time (rambler instance being the exception atm). Even worse, it creates unnecessary overhead without getting the data any faster due to serialization. Creating a large number of requests in a short timeframe also increases chances for HTTP 429 errors.

In additional please also check Rolands comments on this topic: https://lists.openstreetmap.org/pipermail/talk-de/2015-May/111111.html

**Comment by k-nut** [comment]
This is actually exactly what this (unmerged) Pull Request tries to solve: https://github.com/kartenkarsten/leaflet-layer-overpass/pull/28

**Comment by mmd-osm** [comment]
Thanks for the quick feedback!

Hmm, the PR probably needs quick some additional work, as changes repo URLs in bower.json, (C) in LICENSE, refers to a "new fork", etc.

What will be the 'official' repo for the future with the new logic in place?

**Comment by k-nut** [comment]
I guess one could just merge the initial commits that did not refer to a fork yet. Probably depends on when @kartenkarsten finds time (and willingness) to do it.

**Comment by kartenkarsten** [comment]
In the moment I haven't got enough time for this project. Therefore I think future development should be placed at the fork of @GuillaumeAmat. But I'll do for now a last update with PR #30 .

**Comment by GuillaumeAmat** [comment]
Oh no... My PR was clean at the beginning and lately I forgot that my additional commits will messed up this PR.

Sorry, my bad... :/

**Comment by nrenner** [comment]
I made a small [debug page](http://bl.ocks.org/nrenner/61b5f3c3a139f7443e87) ([Gist](https://gist.github.com/nrenner/61b5f3c3a139f7443e87)) to visualize request bounding boxes. Use the layer switcher to compare with different options, also see console for request counts.

The specific problem with briefkastenkarte.de seems to be that it uses [``minzoom: 12``](https://github.com/dbretschneider/briefkastenkarte.de/blob/develop/briefkastenkarte.js#L90) (default: 15), which is two levels lower than the OverPassLayer [``requestZoomLevel= 14``](https://github.com/dbretschneider/briefkastenkarte.de/blob/develop/external/leaflet-layer-overpass/OverPassLayer.js#L168).

Allowing zooms lower than a fixed tiling zoom means that the number of tiles quadruples with each lower level. So at z12 it seems to send hundreds of requests (see second debug layer "minzoom 12")!
