### ISSUE TITLE
Duplicate element skips all remaining tile elements

### ISSUE THREAD

**Issue by nrenner** [kartenkarsten/leaflet-layer-overpass#31]
The [default callback implementation](https://github.com/kartenkarsten/leaflet-layer-overpass/blob/master/src/OverPassLayer.js#L17) exits the loop and function with ``return`` when an element has already been loaded (id in index):

    if (e.id in this.instance._ids) return;

Not sure if this on purpose, but I think it should use ``continue`` to just skip the current element and continue the loop.

See [test page](http://bl.ocks.org/nrenner/ef3ec531767ba8f4cde8) ([Gist](https://gist.github.com/nrenner/ef3ec531767ba8f4cde8)) - note that it's based on the fork. The second layer using ``continue`` displays the second elements as expected, the first omits it for all tiles but the first (when first common element with same id not loaded yet).

cc @GuillaumeAmat

**Comment by GuillaumeAmat** [comment]
You're right, it have to be a `continue` rather than a `return`, though it only matters in my fork when setting the `requestPerTile` to false.
It's corrected in the fork and released under the 1.4.1 version. Can you consider to make a PR on this repo?

Thanks

**Comment by GuillaumeAmat** [comment]
Thank you @nrenner ;)

**Comment by nrenner** [comment]
@GuillaumeAmat Seems like I can't fork your fork to create a PR there, probably a GitHub restriction? Also, issues are disabled, need to be activated in repo settings.

**Comment by GuillaumeAmat** [comment]
@nrenner Ok I made a new repository to fix that. So there is the PR fork here:

https://github.com/GuillaumeAmat/leaflet-layer-overpass

And the « reel » fork for further work here:

https://github.com/GuillaumeAmat/leaflet-overpass-layer
