### ISSUE TITLE
Is it possible to show ways?

### ISSUE THREAD

**Issue by jbouffand** [kartenkarsten/leaflet-layer-overpass#34]
Hello.

Is it possible to show ways (like motorway, etc) using Leaflet Layer OverPass? Or is it show only nodes?

I try to show skiing pistes on a leaflet map. In your demo I changed 

      [query: "node(BBOX)['amenity'='post_box'];out;",]

to

     [query: "way(BBOX)['route'='piste'];out;",]

and I changed

          [var circle = L.circle(pos, 50, {
            color: color,
            fillColor: '#fa3',
            fillOpacity: 0.5
          })
          .bindPopup(popup);
          this.instance.addLayer(circle);]

to

         [var ligne = L.multiPolyline(pos, {
			weight: 5,
            color: 'red'
          })
          .bindPopup(popup);
          this.instance.addLayer(ligne);]

but it didn't work. Is my code wrong? (of course I set the view on a ski resort!)

I have another small question: is it possible to change the minzoom option?

Thanks.

**Comment by kartenkarsten** [comment]
It's possible to show ways as well. Have a look to the ways example in demo folder.
Your code isn't working because a line needs more than a single lnglat position.

To your second question: it's possible see the demo.

**Comment by jbouffand** [comment]
Thanks. I didn't look at the demo folder, I'm sorry!
