### ISSUE TITLE
Add refernce on leaflet plugin website

### ISSUE THREAD

**Issue by k-nut** [kartenkarsten/leaflet-layer-overpass#7]
I would like to add a reference to this project to the [leafelt plugin page](http://leafletjs.com/plugins.html). Are you okay with your project and you github user name listed as a maintainer being on the list?

**Comment by kartenkarsten** [comment]
sure - I planed it myself as well but forgot about it^^
so go ahead

**Comment by k-nut** [comment]
Merged with https://github.com/Leaflet/Leaflet/pull/3117
